spring:
  profiles:
    active: dev
  application:
    name: jesse-client-consumer
---
spring:
  profiles: dev

server:
  port: 9000

management:
  port: 9100
  contextPath: /actuator

eureka:
  statusPageUrlPath: ${management.contextPath}/info
  healthCheckUrlPath: ${management.contextPath}/health
  client:
    serviceUrl:
      defaultZone: http://server1:7000/eureka/
  instance:
    non-secure-port: ${server.port}

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true

ribbon:
  eureka:
    enabled: true

---
spring:
  profiles: test

server:
  port: 9000

management:
  port: 9100
  contextPath: /actuator

eureka:
  statusPageUrlPath: ${management.contextPath}/info
  healthCheckUrlPath: ${management.contextPath}/health
  client:
    serviceUrl:
      defaultZone: http://server1:7000/eureka/
  instance:
    non-secure-port: ${server.port}

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true

ribbon:
  eureka:
    enabled: true
---
spring:
  profiles: prod

server:
  port: 9000

management:
  port: 9100
  contextPath: /actuator

eureka:
  statusPageUrlPath: ${management.contextPath}/info
  healthCheckUrlPath: ${management.contextPath}/health
  client:
    serviceUrl:
      defaultZone: http://server1:7000/eureka/
  instance:
    non-secure-port: ${server.port}

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true

ribbon:
  eureka:
    enabled: true

