

server:
  port: 5000

spring:
  application:
    name: jesse-client-gateway

management:
  port: 5100
  contextPath: /actuator

eureka:
  statusPageUrlPath: ${management.contextPath}/info
  healthCheckUrlPath: ${management.contextPath}/health
  client:
    serviceUrl:
      defaultZone: http://server1:7000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: server2
    non-secure-port: ${server.port}

ribbon:
  eureka:
    enabled: true


zuul:
  host:
    max-per-route-connections: 1000
    max-total-connections: 1000
    socket-timeout-millis: 20000
    connect-timeout-millis: 20000
  routes:
    consumer01:
      sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Methods
      path: /consumer01/**
      serviceId: jesse-client-consumer
    provider:
      sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Methods
      path: /provider/**
      serviceId: jesse-client-provider
